version: "3.9"
services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "7000:8000"
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_HOST=db
      - REDIS_URL=redis://cache:6379/0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cc-wrapper

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - "5000:3000"
    depends_on:
      - backend
    networks:
      - cc-wrapper
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_BACKEND_HOST=https://code-api.tanmaydeepsharma.com
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_OUT_URL=${NEXT_PUBLIC_CLERK_AFTER_SIGN_OUT_URL}
networks:
  cc-wrapper:
    external: true 

